### ISSUE TITLE
Artifactory NPM publish doesnt work

### ISSUE THREAD

**Issue by miguel258** [jfrog/artifactory-vsts-extension#107]
I'm tried to publish artifact from Azure devops using Artifactory NPM task and command pack and publish, and have error, this fails from today.

Attach support image.

![image](https://user-images.githubusercontent.com/13203929/68242872-51ff8180-ffdf-11e9-96f7-c8ad4c2ab175.png)

**Comment by eyalbe4** [comment]
@miguel258,
Can you please see if you version 1.7.2 of the JFrog Atifactory Extension installed?
This bug was introduced on version 1.7.0 but fixed on 1.7.2.
Looking forward to your reply.

**Comment by miguel258** [comment]
Hi, the installed version is 1.7.2, but when use the task the execution log
notify that stay using version 1.7.1
Thanks

**Comment by eyalbe4** [comment]
@miguel258,
Are you still experiencing this issue with the latest release?

**Comment by eyalbe4** [comment]
@miguel258,
I'm closing this issue for now, but do let us know if you still need assistance with this.
