### ISSUE TITLE
JFrog .NET Core push nuget include local path and not put it on the root on the repo

### ISSUE THREAD

**Issue by benbalki** [jfrog/artifactory-vsts-extension#303]
**Description**
When using JFrog .NET Core\ JFrog Nuget for NuGet push to an Artifactory repo, the NuGet package is not uploaded to the root of the repo, when the relative path is "", but uploaded with the NuGet local path on the agent machine.
(i.e. <repo-name>/azp/workdir/1/a/<NuGet package>)

**To Reproduce:**
run task when pathToNupkg = /azp/workdir/1/a/*.nupkg and targetDeployPath = "".

**Actual behaviour:**
packages are uploaded to path <repo-name>/azp/workdir/1/a/<NuGet package>.

**Expected behavior:**
packages are uploaded to path <repo-name>/<NuGet package>.

**Screenshots**

**Versions**
- JFrog Azure DevOps Extension version: 1.0.2
- JFrog CLI version: 2.10.1
- Agent operating system: Ubuntu
- JFrog Artifactory version: 6.4.1

**Comment by benbalki** [comment]
@RobiNino - when will this update be merged into the release branch (V2)?
And is there a workaround to perform till that time?

**Comment by RobiNino** [comment]
Hi @benbalki ,
Thanks for reporting this.
JFrog Extension version 2.0.3 was just released and includes the fix.
We'd appreciate your feedback for it.

**Comment by benbalki** [comment]
Hi @RobiNino,
Thanks for the quick fix.
I've verified it's working on the JFrog .NET Core task, and since the code is similar no reason it shouldn't work on the JFrog Nuget task.

Thanks,
