### ISSUE TITLE
JFrog Tools Installer does not work if version not in the cache

### ISSUE THREAD

**Issue by Tobias-08** [jfrog/artifactory-vsts-extension#337]
**Describe the bug**
- the V2 version of the tools installer does not work if the version is not in the cache and has to be downloaded from the configured feed
- error is

```
Downloading: https://[...]/[...]-jfrogcli-remote/2.16.0/jfrog-cli-windows-amd64/jf.exe
##[error]Error occurred while executing task:
Failed while attempting to download JFrog CLI from https://[...]/[...]-jfrogcli-remote/2.16.0/jfrog-cli-windows-amd64/jf.exe. If the chosen Artifactory Service cannot access the internet, you may also manually download version 2.16.0 of JFrog CLI and place it on the agent in the following path: E:\BA\A3\_work\_tool\_jf\current\jf.exe
Error: Unexpected HTTP response: 404
```

- the same configuration works with the V1 version of the task

**Expected behavior**
- the V2 tools installer should install the version correctly even if it is not yet in the cache

**Versions**
- JFrog Azure DevOps Extension version: 2.1.1
- Agent operating system: Windows
- JFrog Artifactory version: 7.27.15

**Comment by RobiNino** [comment]
Hi @Tobias-08,
Note that the Tools Installer task of the new extension expects the JFrog CLI's Remote repository to be pointing to `https://releases.jfrog.io/artifactory/jfrog-cli/v2-jf/`, unlike the task in the old extension.
Please let me know if this fixes the issue for you.
Thanks

**Comment by Tobias-08** [comment]
Hi @RobiNino,
I missed that but even with the URL you mentioned the problem is still the same.

**Comment by RobiNino** [comment]
@Tobias-08 ,
We are unable to reproduce it on a new remote repository, on any OS, with multiple JFrog CLI versions.
Please verify your configuration again, or provide some details about your environment to help us reproduce.
Thanks

**Comment by Tobias-08** [comment]
@RobiNino
Hm, strange. I checked our configuration again and I'm not aware of any errors.
Does the remote repository need to have any special configuration (except the URL)?
Has anything else changed how the V2 task handles the download? Maybe proxy-configuration (our agents are behind a corporate proxy, a bypass-rule is configured for the internal Artifactory with the remote feed)? Our agents are hosted on Windows.

**Comment by RobiNino** [comment]
@Tobias-08 
The remote repository doesn't require a special configuration, and I'm unaware of anything related changing between the extensions.
Could you verity that the bypass-rule is not on a specific URL but on the domain (or update its URL)?

**Comment by Tobias-08** [comment]
@RobiNino 
It was my mistake: I missed to configure the proxy on the remote repository (`advanced/network/proxy`). It works now.

Thanks!
