### ISSUE TITLE
When will the Artifactory Docker task be migrated to the new extension?

### ISSUE THREAD

**Issue by ashokm** [jfrog/artifactory-vsts-extension#342]
As per the information on https://www.jfrog.com/confluence/display/JFROG/Artifactory+Azure+DevOps+Extension:
> The Artifactory Docker task hasn't yet been migrated to the new extension. This is because we're currently working on further improving JFrog CLI's integration with the docker client, and would like to expose the new docker functionally to the new extension once that effort is completed. As the old extension is here to stay, you can continue using its Artifactory Docker task.

Is there a ETA on when the Docker task will be available in the new extension (https://www.jfrog.com/confluence/display/JFROG/JFrog+Azure+DevOps+Extension)?

This would be useful information so users can plan/understand how long they can have to keep the old extension installed before being able to fully deprecate it and use the new extension 100%.

**Comment by sverdlov93** [comment]
Hi @ashokm and @mrweiland ,
We have just released extension version 2.2.0 which includes Docker Pull, Docker Push, and Docker Scan tasks.
We'd appreciate your feedback on it.
Thanks!

**Comment by ashokm** [comment]
I just saw the release. Thanks!

**Comment by sverdlov93** [comment]
@ashokm please notice that the minimum supported Artifactory version for the new docker Pull/Push tasks is 7.33.3.
