### ISSUE TITLE
Folder structure should be maintained when downloading the artifacts via Azure DevOps release pipeline 

### ISSUE THREAD

**Issue by sandeepanikapati** [jfrog/artifactory-vsts-extension#354]
**Is your feature request related to a problem? Please describe.**

When downloading the artifacts via the Azure DevOps release pipeline, the artifacts always download flattened artifacts without any folder structure.
 
Steps to reproduce:
 
1) Publish the build with artifacts along with the folder structure.
2) Create an Azure DevOps Release -> add artifact of type “Artifactory” or  “Artifactory V2” with the build name and number (created on Step 1).
3) Run the build and verify the folder structure of the downloaded artifacts. 

**Describe the solution you'd like to see**
Providing an ability to maintain the folder structure of the downloaded artifacts while downloading via Artifactory Azure DevOps release pipeline. 

**Describe alternatives you've considered**
NA

**Additional context**

<img width="427" alt="folders_structure" src="https://user-images.githubusercontent.com/66374485/178240103-9bbeced0-e16c-48c0-8684-70eed76fb854.png">

<img width="1792" alt="Azure_release_pipeline_new" src="https://user-images.githubusercontent.com/66374485/178240149-65e46d7f-b6ce-4f77-8b7b-da5566bf9cf3.png">

![Azure_output_new](https://user-images.githubusercontent.com/66374485/178240188-8260581c-44b9-4562-b4d1-0f57023dec62.png)

**Comment by sverdlov93** [comment]
Hi @sandeepanikapati ,
Jfrog Azure DevOps Extension 2.3.0 is released and contains the above feature request.
Looking forward to your feedback on it.
