### ISSUE TITLE
Outdated migration information for the Docker task

### ISSUE THREAD

**Issue by ashokm** [jfrog/artifactory-vsts-extension#356]
The following page needs to be updated now that there is an available '**JFrog Docker**' task in the [new extension](https://www.jfrog.com/confluence/display/JFROG/JFrog+Azure+DevOps+Extension):

- [Artifactory Azure DevOps Extension](https://www.jfrog.com/confluence/display/JFROG/Artifactory+Azure+DevOps+Extension)

The above page still says:
> The **Artifactory Docker** task hasn't yet been migrated to the new extension. This is because we're currently working on further improving JFrog CLI's integration with the docker client, and would like to expose the new docker functionally to the new extension once that effort is completed. As the old extension is here to stay, you can continue using its **Artifactory Docker** task.

Also the '[New vs. old tasks](https://www.jfrog.com/confluence/display/JFROG/Artifactory+Azure+DevOps+Extension#ArtifactoryAzureDevOpsExtension-Newvs.oldtasks)' section has also not been updated to show that users can migrate away from the old '**Artifactory Docker**' task in the [old extension](https://www.jfrog.com/confluence/display/JFROG/Artifactory+Azure+DevOps+Extension) to the '**JFrog Docker**' task in the [new extension](https://www.jfrog.com/confluence/display/JFROG/JFrog+Azure+DevOps+Extension).

**Comment by RobiNino** [comment]
Updated, thanks a lot!
