### ISSUE TITLE
Howto overwrite BuildName TFS/VSTS

### ISSUE THREAD

**Issue by Kreism** [jfrog/artifactory-vsts-extension#37]
Hi
If we publish build Informations we do not have the possibility to change the Name of the Build Definition. The tasks always uses Build.DefinitionName
Is there a possibility to change this behavior?
Thanks
Martin

**Comment by RobiNino** [comment]
Hi @Kreism,
Our latest release (1.5.0) includes this functionality.
We'd appreciate your feedback for it.
Thanks
