### ISSUE TITLE
Azure DevOps Extensions

### ISSUE THREAD

**Issue by natebunton** [jfrog/artifactory-vsts-extension#378]
What is the difference between these Azure DevOps extensions and which one is preferred to be used?  They both point to the same GitHub Repo

https://marketplace.visualstudio.com/items?itemName=JFrog.jfrog-artifactory-vsts-extension (Initial Release: 7/30/2018)

https://marketplace.visualstudio.com/items?itemName=JFrog.jfrog-azure-devops-extension (Initial Release: 1/2/2022)

**Comment by RobiNino** [comment]
Hi @natebunton ,
The latter, [JFrog Azure DevOps Extension](https://marketplace.visualstudio.com/items?itemName=JFrog.jfrog-azure-devops-extension), is the newer extension and the recommended one.
[JFrog Azure DevOps Extension Documentation](https://www.jfrog.com/confluence/display/JFROG/JFrog+Azure+DevOps+Extension).
You can read about the differences and motivation to create the new extension [here](https://www.jfrog.com/confluence/display/JFROG/Artifactory+Azure+DevOps+Extension#ArtifactoryAzureDevOpsExtension-WeCreatedaNewExtension).
