### ISSUE TITLE
Empty Principal information

### ISSUE THREAD

**Issue by Kreism** [jfrog/artifactory-vsts-extension#38]
Hi
The build build info Task does not publish the Principal information
![image](https://user-images.githubusercontent.com/1275204/45811414-5084d400-bccd-11e8-9a9f-9f751e367c26.png)

Old Version was fine:
![image](https://user-images.githubusercontent.com/1275204/45811499-8cb83480-bccd-11e8-8739-d4c858908d17.png)

Could you please fix this. Thanks
Martin

**Comment by eyalbe4** [comment]
@Kreism,
This has been added and you should be able to see the principal information as part of the build-info.
Please let us know if this works for you.
