### ISSUE TITLE
JFrogMaven 1.4.0 causes 401 Authentication is required

### ISSUE THREAD

**Issue by Slooz** [jfrog/artifactory-vsts-extension#381]
### Describe the bug

JFrogMaven 1.4.0 causes 401 Authentication is required. JFrogMaven 1.3.0 works fine.

### Current behavior

[JFrogMaven.1.4.0.txt](https://github.com/jfrog/jfrog-azure-devops-extension/files/10865235/JFrogMaven.1.4.0.txt)

### Azure DevOps extension name and version

JFrog 2.4.0

### JFrog CLI version

2.34.5

### Operating system type and version

Ubuntu 22.04.2 LTS

**Comment by omerzi** [comment]
Hi @Slooz, this issue should have been resolved in [v2.4.1](https://github.com/jfrog/jfrog-azure-devops-extension/releases/tag/2.4.1), please let us know if everything works as expected.
