### ISSUE TITLE
Service Connection Usernames should not be marked confidential

### ISSUE THREAD

**Issue by davidcorrigan714** [jfrog/artifactory-vsts-extension#394]
### Describe the bug

When using the Azure DevOps UI to configure service connections, or when using the API to retrieve details about service connections the username is treated as sensitive data leading to masking in the UI and empty fields in API calls. I'm currently working on adding these to the Azure DevOps Terraform provider and this was a bit of a surprise discovered during testing.

### Current behavior

When using the Azure DevOps UI to configure service connections, or when using the API to retrieve details about service connections the username is treated as sensitive data leading to masking in the UI and empty fields in API calls.

### Expected behavior

The username should be visible in the UI and the API should return the associated username. This should be a simple fix in vss-extension.json. Seems like if isConfidential is ommitted from the field definition it defaults to True, so just adding `"isConfidential": false` to the username field definitions should do the trick.

### Azure DevOps extension name and version

JFrog 2.4.2

### JFrog CLI version

NA

### Operating system type and version

NA

**Comment by sverdlov93** [comment]
Hi @davidcorrigan714 
Thanks for reporting this issue.
This PR - https://github.com/jfrog/jfrog-azure-devops-extension/pull/395 should fix it.
I will update this thread once the next release will be out.

**Comment by sverdlov93** [comment]
Hi @davidcorrigan714 
https://github.com/jfrog/jfrog-azure-devops-extension/releases/tag/2.5.0  is released and should fix the above issue.
Looking forward to your feedback on it.
