### ISSUE TITLE
Add working directory for step Collect issues from Git

### ISSUE THREAD

**Issue by Jan-Pleva** [jfrog/artifactory-vsts-extension#396]
**Is your feature request related to a problem? Please describe.**
Yes, we are not abble to use step Collect issues with more checkuot repositories.
Step: Checkout hello10@feature/jfrog to s/hello10
Step: Checkout build-templates@main to s/build-templates
Step: JFrog Collect Build Issues 15:52:23 [Error] Could not find .git

Azure DevOps create folder for each check out.

**Describe the solution you'd like to see**
Add the working directory option to the Collection step.

**Describe alternatives you've considered**
Only use CLI step.

**Additional context**
In the documentation it is calle ".git path"
https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-CollectingBuild-Info

**Comment by sverdlov93** [comment]
@jathok 
[jfrog-azure-devops-extension 2.6.0](https://github.com/jfrog/jfrog-azure-devops-extension/releases/tag/2.6.0) is released and it contains the above functionality.
Looking forward to your feedback on it.
