### ISSUE TITLE
Task JFrog CLI V2 - [Error] flag provided but not defined: -server-id

### ISSUE THREAD

**Issue by Jan-Pleva** [jfrog/artifactory-vsts-extension#403]
### Describe the bug

The yarn command reseive parametr -serve-id, but this parametr is not use.
[Error] flag provided but not defined: -server-id

### Current behavior

Put the right parametr -server-id-resolve or change the yarn step expectation.

### Reproduction steps
-----
Starting: JFrog YARN config
Task         : JFrog CLI V2
Description  : Run your own JFrog CLI command.
Version      : 1.4.1
Author       : JFrog
Help         : [More Information](https://www.jfrog.com/confluence/display/JFROG/JFrog+Azure+DevOps+Extension#JFrogAzureDevOpsExtension-ExecutingJFrogCLICommands)
-----
Found tool in cache: jf 2.34.6 x64
Running jfrog-cli from /__t/jf/2.34.6/x64/jf.
JFrog CLI version: 2.34.6
Executing JFrog CLI Command: /__t/jf/2.34.6/x64/jf c add "OFCI.ofci-frontend_20230413.10_jfrog_cli_cmd_1681388908685" --url="[https://artifactory.skoda.vwgroup.com/"](https://artifactory.skoda.vwgroup.com/%22) --interactive=false --access-token=***
Executing JFrog CLI Command: /__t/jf/2.34.6/x64/jf c use "OFCI.ofci-frontend_20230413.10_jfrog_cli_cmd_1681388908685"
12:28:28 [Info] Using server ID 'OFCI.ofci-frontend_20230413.10_jfrog_cli_cmd_1681388908685' (https://artifactory.skoda.vwgroup.com/).
Executing JFrog CLI Command: /__t/jf/2.34.6/x64/jf yarn-config --repo-resolve=front-npm-virtual --server-id="OFCI.ofci-frontend_20230413.10_jfrog_cli_cmd_1681388908685"
**Incorrect Usage: flag provided but not defined: -server-id**

Name:
  jf yarn-config - Generate Yarn configuration.

Usage:
  jf yarn-config [command options]
  
Options:
  --global               [Default: false] Set to true if you'd like the configuration to be global (for all projects). Specific projects can override the global configuration.
  --repo-resolve         [Optional] Repository for dependencies resolution.
  **--server-id-resolve**    [Optional] Artifactory server ID for resolution. The server should configured using the 'jfrog c add' command.
12:28:28 [Error] flag provided but not defined: -server-id
  

##[error]Error: Command failed: /__t/jf/2.34.6/x64/jf yarn-config --repo-resolve=front-npm-virtual --server-id="OFCI.ofci-frontend_20230413.10_jfrog_cli_cmd_1681388908685"
Executing JFrog CLI Command: /__t/jf/2.34.6/x64/jf c remove "OFCI.ofci-frontend_20230413.10_jfrog_cli_cmd_1681388908685" --quiet
Finishing: JFrog YARN config

![image](https://user-images.githubusercontent.com/71633160/231767561-75cbf04a-6f8d-406e-8cc8-6435e761009a.png)

### Azure DevOps extension name and version

Task JFrog CLI V2

### JFrog CLI version

2.34.6

### Operating system type and version

Linux

**Comment by Jan-Pleva** [comment]
<html>
<body>


-server-id-resolve | [Optional]Artifactory server ID for resolution. The server should configured using the 'jf c add' command.
-- | --



</body>
</html>
https://jfrog.com/help/r/jfrog-cli/building-npm-packages-using-the-yarn-client

**Comment by sverdlov93** [comment]
Hi @Jan-Pleva,
Thanks for reporting this issue.
Our apologies for the inconvenience caused by this.
The JFrog CLI task adds configures the JFrog server configuration and adds the `--server-id` flag automatically to the requested task.
Some build tool commands (such as 'jf yarn') are not supporting that flag.
We should fix that issue soon.

**Comment by Jan-Pleva** [comment]
Hi, I find the problem with the JFrog CLI extension as global problem...not yarn problem.
![image](https://github.com/jfrog/jfrog-azure-devops-extension/assets/71633160/d845c7a3-3f58-4893-acc9-a08d3ee8a40e)

**Comment by sverdlov93** [comment]
@Jan-Pleva 
The following [PR](https://github.com/jfrog/jfrog-azure-devops-extension/pull/411) will resolve that.
I will update this thread once the next release will be out.

**Comment by sverdlov93** [comment]
@jathok 
[jfrog-azure-devops-extension 2.6.0](https://github.com/jfrog/jfrog-azure-devops-extension/releases/tag/2.6.0) is released and should fix the above issue.
Looking forward to your feedback on it.

**Comment by Jan-Pleva** [comment]
Hi, I check that, It is now ok. Thank you.
