### ISSUE TITLE
Need to be able to specify JDK for Gradle builds

### ISSUE THREAD

**Issue by drobert-bfm** [jfrog/artifactory-vsts-extension#423]
Using the native Gradle@2 plugin, there is an option to specify the jdk version for the build ('JavaHomeVersion', 'jdkVersionOption', 'jdkArchitectureOption'). No such options seem to exist in the JFrog Gradle plugin. 

Right now, it seems to be picking up Java 11, which breaks some of our builds which are still dependent on Java 8. We can build using the native Gradle plugin, but not with the JFrog one.

**Comment by sverdlov93** [comment]
Hi @vmiko, 
[JFrog Azure Devops 2.7.0](https://github.com/jfrog/jfrog-azure-devops-extension/releases/tag/2.7.0) is released and should fix the above issue.
Looking forward to your feedback on it.

**Comment by sverdlov93** [comment]
Hi @drobert-bfm ,
[JFrog Azure Devops 2.7.0](https://github.com/jfrog/jfrog-azure-devops-extension/releases/tag/2.7.0) is released and should fix the above issue.
Looking forward to your feedback on it.
