### ISSUE TITLE
Update CLI Version included with the plugin to 2.43 to fix special character bug.

### ISSUE THREAD

**Issue by NandiniDJFrog** [jfrog/artifactory-vsts-extension#438]
**Is your feature request related to a problem? Please describe.**
Requesting to upgrade the CLI version included with the DevOps Extension in order to fix this bug.

https://github.com/jfrog/jfrog-cli/issues/2079

**Describe the solution you'd like to see**

See above.

**Describe alternatives you've considered**

Recommending use cliVersion flag by support.

**Comment by sverdlov93** [comment]
Hi @NandiniDJFrog , new Extension version is released with JFrog CLI 2.44.1!
