### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by AlphaCluster** [jfrog/artifactory-vsts-extension#44]
So when using the extension I am getting the "x509: certificate signed by unknown authority" error. At the same time if I login to the box I can run the command line version that matches and it works fine? Seems like the extension is doing something to prevent the .jfrog folder next to the jfrog.exe from being read and also does not seem to interpret JFROG_CLI_HOME.

**Comment by yahavi** [comment]
@AlphaCluster, thanks for reporting this issue.
In order to help with the investigation, please provide the following information:
1. The task name.
2. The error output from the beginning of the line to the end of it. 
3. Do you know if problem started now with the latest release (1.2.1) from October 8th?

Thanks!

**Comment by AlphaCluster** [comment]
1. Artifactory Generic Upload
2. [Error] Put https://<server url>: x509: certificate signed by unknown authority
3. Don't know as this is the first time I used the extension.
4. No proxies are involved i manually setup the jfrog cli and pushing the package locally.

I have environment variables set on the build server to point to the .jfrog folder as it doesn't seem to pickup the .jfrog folder as would be expected and that will run the same command if I run it in powershell.

**Comment by yahavi** [comment]
@AlphaCluster,
There is a known [issue](https://github.com/jfrog/jfrog-cli-go/issues/172) with `JFROG_CLI_HOME` environment variable. The `JFROG_CLI_HOME` interpreted as the directory that contains the `.jfrog` folder.
Please make sure that JFROG_CLI_HOME is the folder that contains the `.jfrog` folder, not the `.jfrog` itself.
Please let me know if it helped.

Also - in the beginning of the task, there are the version of the task and JFrog-CLI (`Version` and `JFrog CLI version`). Can you write them here?

Thanks.

**Comment by AlphaCluster** [comment]
Sorry, I took so long to get back on this. I have tried it with the folders both way. I have gotten everything working I believe using the ENV variables when I use the command line myself on the build agent. It is only giving me errors when I run it via a TFS task.

**Comment by eyalbe4** [comment]
@AlphaCluster,
Can you please let me know if this is still an issue with the latest release of the extension?

**Comment by AlphaCluster** [comment]
The latest release seems to have fixed this issue.

**Comment by abhijit-dey5** [comment]
Hi All, I am facing the same issue in Azure pipeline task (i.e. Artifactory Generic Upload)

However, I am using 3 different agents in my Azure DevOps Project and two of them are executing the task successfully. It is an issue in only one agent.

Can you help me with any clues?
