### ISSUE TITLE
Artifactory NuGet Restore for multiple repositories

### ISSUE THREAD

**Issue by OleksiiAkishev** [jfrog/artifactory-vsts-extension#460]
Is it possible to use an Artifactory NuGet Restore with multiple Repositories(targetResolveRepo) when the Job is built based on the TFS in the classic editor. Same as for the Nuget restore task by pointing to the sln file or NuGet config. When using the Artifactory NuGet Restore task it gives opportunity to choose only one repo from many. 
Or at least is it possible to do that for the YAML and Git repo?

**Comment by DavidRadoorHummel** [comment]
Why on earth would you do that? Use a[ virtual repository in Artifactory](https://jfrog.com/help/r/jfrog-artifactory-documentation/set-up-virtual-nuget-repositories). That is literally why they exist.

**Comment by OleksiiAkishev** [comment]
Hello, thank you very much for your answer.
It is helpful.

Could you please advise if it possible to use an Artifactory Nuget restore
task (by pointing to the virtual repository), then the MSBuild restore task
expected to be used on the Azure pipe job?

The problem is happening during the Artifactory Nuget restore task
execution. For some packages I got an error: Failed to download package,
response status 504.

The point that the restore is working well on the local machine while using
nuget restore with nuget CLI with added personal access token for the
private feed. But on building pipeline it always fails.

Could it be the problem with the token which was provided for pipeline
build or Artifactory server issue?

Thank you!

пт, 24 лист. 2023, 09:51 користувач David Radoor Hummel <
***@***.***> пише:
