### ISSUE TITLE
VSTS artifactory and artifact layout

### ISSUE THREAD

**Issue by gopalramadugu** [jfrog/artifactory-vsts-extension#47]
Does the VSTS artifactory plugin support sending tokens for artifact layout ? This is an option in UI of artifactory. This is listed as Layout Tokens with org, module ,baseRev etc in Artifactory.

**Comment by gopalramadugu** [comment]
@eyalbe4 No not Access tokens. I am taking about artifact layout view. when uploading the jar through the plugin the Module ID and Dependency Declaration are not populated. These are empty.

**Comment by eyalbe4** [comment]
@gopalramadugu,
Are you using the *Artifactory Maven* task to build and deploy the jar? Are you deploying it to a maven repository in Artifactory?

**Comment by gopalramadugu** [comment]
@eyalbe4  We are using Gradle repository in Artifactory.  We are using gradle build task to build it and upload using the Artifactory Generic Uplaod plugin by specifying target path.

**Comment by eyalbe4** [comment]
Thanks @gopalramadugu.

I haven't tried using the *Artifactory Generic Upload* task (which at the end sends a simple PUT request to Artifactory) to upload artifaxts to a Gradle Repository. I think it should work, and set the properties properly, providing the upload path completely matches the expected Gradle Repository layout. Could it be that the upload path you configured in the File Spec should be modified? Let me give it a try and I'll let you know if this works.

In any case, we should properly add an *Artifactory Gradle* task to VSTS, similarly to the existing *Artifactory Maven* task.

**Comment by eyalbe4** [comment]
@gopalramadugu,
Do you still need assistance with this?

**Comment by gopalramadugu** [comment]
No you can close this. We are using maven plugin instead of gradle plugin which works.
