### ISSUE TITLE
Enable env vars in file spec

### ISSUE THREAD

**Issue by gereon77** [jfrog/artifactory-vsts-extension#48]
Hi guys,

I want to upload a created a zip archive called "$(System.TeamProjectId)_$(Build.BuildId).zip" with the Generic Upload task. Unfortunately I see no way to use variables in the json spec. "*.zip" doesn't work as my ArtifactsDirectory contains additional zips I don't want to upload.

Thank you in advance and
best regards,

Gereon

**Comment by DimaNevelev** [comment]
@gereon77,
Did you try the following spec?
```
{
  "files": [
    {
      "pattern": "$(System.TeamProjectId)_$(Build.BuildId).zip",
       "target": "YOUR_REPO/SOME_PATH/"
    }
  ]
}
```
Currently, only the task configuration spec support variables.

**Comment by gereon77** [comment]
Yes. I use exactly this spec and when I tried it the first time it failed because no artifacts were uploaded. Error message was "Could not find file $(System.TeamProjectId)_$(Build.BuildId).zip". I tried it again right now and it worked as expected. This issue can be closed.

Thanks.
