### ISSUE TITLE
Add optional jfrog cli parameters for the Artifactory Nuget Azure DevOps task

### ISSUE THREAD

**Issue by mcgurksean** [jfrog/artifactory-vsts-extension#480]
When uploading artifacts to Artifactory from Azure Devops using the Artifactory Nuget Azure DevOps task, it would be useful to download artifacts to the exact target path specified and their hierarchy in the source repository be ignored.

For this, the `--flat="true"` option needs to be able to be set via the jfrog CLI.

Is there a way that optional jfrog cli parameters can be added for the Artifactory Nuget Azure Devops task so that the --flat="true" option can be specified?

**Comment by mcgurksean** [comment]
N.B. This is the case when you choose the 'push' command from here:

![377fb48a-30bc-4d2a-a35e-5203b6507aa8](https://github.com/jfrog/jfrog-azure-devops-extension/assets/1913745/8d9595c3-69e9-437e-9f88-bab1c624e1cf)

When this command is chosen, the ability to add additional arguments is not available.

**Comment by sverdlov93** [comment]
Hi @mcgurksean , the Nuget push task [adds](https://github.com/jfrog/jfrog-azure-devops-extension/blob/395e5398f9cf9e736b11984d4ac70715bbf32ac8/tasks/JFrogNuget/nugetBuild.js#L92) `--flat=true` by default.
