### ISSUE TITLE
Invalid character 'A' in string escape code

### ISSUE THREAD

**Issue by dbuckingham** [jfrog/artifactory-vsts-extension#5]
We are trying to use the Generic Upload task to upload to Artifactory and are always met with an error.  Our agent is running on a Windows server.

Our file spec is below:
{
  "files": [
    {
      "pattern": "$(Build.SourcesDirectory)\ci-utils\pom.xml",
      "target": "libs-release-local/test/"
    }
  ]
}

When the variable is expanded, our file spec looks like this:
{
  "files": [
    {
      "pattern": "E:\Agents\11\_work\331\s\ci-utils\pom.xml",
      "target": "libs-release-local/test/"
    }
  ]
}

When we execute this build, the Artifactory step fails with the error:

invalid character 'A' in string escape code

It seems that the task assumes that the agent may be running on a Linux host and cannot properly handle Windows paths.

**Comment by yahavi** [comment]
@dbuckingham,
Thanks for reporting this issue.
We are looking into it.

**Comment by yahavi** [comment]
@dbuckingham,
Just wanted to update you that we managed to reconstruct the issue and are working on a fix.

**Comment by yahavi** [comment]
@dbuckingham, artifactory-vsts-extension 1.0.3 is released and includes a fix for that issue.
The fix replaces single backslashes to double backslashes.
