### ISSUE TITLE
Plugin doesn't work without /artifactory in the url path

### ISSUE THREAD

**Issue by AlphaCluster** [jfrog/artifactory-vsts-extension#50]
So none of the task features (looking up feeds in artifactory or the verify even) work if you have removed the /artifactory from the url being used by artifactory. This causes the /api/plugin endpoint to fail because the url cannot be url//api/plugin.

**Comment by eyalbe4** [comment]
@AlphaCluster,
Why were you trying to remove the /artifactory from the URL?

**Comment by AlphaCluster** [comment]
I am not trying to remove it the configuration I am integrating the VSTS plugin with doesn't have that part of the path. Artifactory should be able to be deployed behind a reverse proxy and it still work. I guess I don't get why the plugin things it needs to a / to the uri for artifactory if it's not already there?

**Comment by AlexeiVainshtein** [comment]
Hi @AlphaCluster

I've tried this on my end without Artifactory in my path and it worked:

![ping_result](https://user-images.githubusercontent.com/13715319/48556615-27f41180-e8ed-11e8-892f-57ea633b05a9.jpg)

I'm using URL that is behind a reverse proxy without Artifactory in my path. Can you please let us know the entire URL that you are pointing to? Does your URL looks like this: https://url.to.Artifactory and the reverse proxy is bypassing the request?

**Comment by AlphaCluster** [comment]
Yeah the url is just the dns name so for your example it if the server was orignally configured as http://example.com:8080/artifactory the reverse proxy is changing it to https://example.com and http://example.com. Since it doesnt have a trailing /artifactory or anything like that it fails cause it try's to validate against what would be  https://example.com//api/plugin

**Comment by joeced** [comment]
This can be closed now. It was fixed with #87.
