### ISSUE TITLE
Update JFrogNpm@1 Task to Use Supported Node Version in Azure DevOps Pipelines

### ISSUE THREAD

**Issue by ashokm** [jfrog/artifactory-vsts-extension#512]
We are receiving the following warning in our Azure DevOps pipelines when using the **JFrogNpm@1** task:

```
##[warning]Task 'JFrog npm' version 1 (JFrogNpm@1) is dependent on a Node version (10) that is end-of-life. Contact the extension owner for an updated version of the task. Task maintainers should review Node upgrade guidance: https://aka.ms/node-runner-guidance
```

This issue seems similar to [aws-toolkit-azure-devops#566](https://github.com/aws/aws-toolkit-azure-devops/issues/566), where upgrading to a current Node.js version is recommended to ensure continued support and security compliance.

As Node 10 is end-of-life, can you provide an update on when the task will be updated to use a supported Node.js version, in line with Microsoft’s [Node upgrade guidance](https://aka.ms/node-runner-guidance)?

**Comment by TobiasBreuer** [comment]
Please note that this is not limited to the JFrogNpm Task but e.g. also affects the ArtifactoryDocker task for example
> Task 'Artifactory Docker' version 1 (ArtifactoryDocker@1) is dependent on a Node version (10) that is end-of-life....

**Comment by owen-delaney-admiral** [comment]
Also seeing it for JFrogPip@1, JFrogPublishBuildInfo@1 & JFrogBuildScan@1 tasks

**Comment by philippk80** [comment]
JFrogDotnetCore (1.10.1) too

**Comment by PratMoha** [comment]
ArtifactoryGenericDownload@1,  ArtifactoryNuGet@2 are also affected since last week.

**Comment by eyalbe4** [comment]
Dear all,
Following the requests here, we released version [2.10.3](https://github.com/jfrog/jfrog-azure-devops-extension/releases/tag/2.10.3), which upgrade the tasks Node version from 10 to 16. @johnpp143 however reports in https://github.com/jfrog/jfrog-azure-devops-extension/issues/517 that this change causes failures in older pipeline agents.
We'd love to get your insights and ideas about the best approach forward.

**Comment by d4nuu8** [comment]
Node 16? This is EOL since September, 11th 2023.

**Comment by johnpp143** [comment]
@eyalbe4 According to migration document, https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/migrateNode16.md,
globally node v20 is supported for the task runner. If users have older version of azure agents, then there is a possibility that version 16 of node task runner will not be supported. Since this update affects all versions of the extension and not only the released version, i think if we can update the execution node like below, it would still support users with old azure build agents, while the newer versions will pick up Node16/20.
"execution": {
  "Node10": {
    "target": "bash.js",
    "argumentFormat": ""
  },
  "Node16": {
    "target": "bash.js",
    "argumentFormat": ""
  }
}

**Comment by eyalbe4** [comment]
Thanks for suggesting the solution @johnpp143 and thanks for contributing the fix @hanankem - https://github.com/jfrog/jfrog-azure-devops-extension/pull/518.
Version 2.10.4 is now released.

**Comment by ashokm** [comment]
LGTM with tasks running with the [JFrog](https://marketplace.visualstudio.com/items?itemName=JFrog.jfrog-azure-devops-extension) marketplace extension version 2.10.4.

Before:
```
Downloading task: JFrogNpm (1.10.1)
##[warning]Task 'JFrog npm' version 1 (JFrogNpm@1) is dependent on a Node version (10) that is end-of-life. Contact the extension owner for an updated version of the task. Task maintainers should review Node upgrade guidance: https://aka.ms/node-runner-guidance
```

Now (no warnings are shown and our pipelines run as expected):
```
Downloading task: JFrogNpm (1.10.4)
```

Thanks!
