### ISSUE TITLE
Artifactory npm fails with minimum required version message

### ISSUE THREAD

**Issue by marcwittke** [jfrog/artifactory-vsts-extension#64]
```
##[section]Starting: Artifactory npm install
==============================================================================
Task         : Artifactory npm
Description  : Install, pack and publish npm packages from and to Artifactory while allowing to collect build-info. The collected build-info can be later published to Artifactory by the "Artifactory Publish Build Info" task.
Version      : 1.4.1
Author       : JFrog
Help         : [More Information](https://www.jfrog.com/confluence/display/RTF/Npm+Registry)
==============================================================================
Downloading: https://api.bintray.com/content/jfrog/jfrog-cli-go/1.23.1/jfrog-cli-windows-amd64/jfrog.exe?bt_package=jfrog-cli-windows-amd64
Caching tool: jfrog 1.23.1 x64
Running jfrog-cli from C:\Server\vstsagent\work\_tool\jfrog\1.23.1\x64\jfrog.exe.
JFrog CLI version: 1.23.1
[Info] Running npm Install.
[Error] This operation requires Artifactory version 5.5.2 or higher.
##[error]Error: Command failed: C:\Server\vstsagent\work\_tool\jfrog\1.23.1\x64\jfrog.exe rt npmi "npm" --url="https://hub.chemaxon.com/artifactory" --user=*** --password=***
```

Chemaxons artifactory has the following version:
![image](https://user-images.githubusercontent.com/4075651/51214139-d28fad00-18fb-11e9-9c15-08f6e79912d6.png)

So it should work.

**Comment by eyalbe4** [comment]
@marcwittke,

The Artifactory Extension utilises JFrog CLI to execute npm. JFrog CLI first validates that Artifactory has the minimum version to support this operation. It does that by sending a GET request to Artifactory, which returns the Artifactory version as a response header. The version is then extracted from the header and compared to the minimum supported version.

We tested this functionality locally, and saw that it is working as expected. We're curious to see which header value is returned to your build agent. Could it be that the header is removed by a proxy between Artifactory and the build agent?

Checking this is pretty easy:
You can run the below cUrl command to get the header value. Replace **(username)**, **(password)**, **(protocol)** (http or https) and **(domain)** (your Artifactory instance domain).
```
curl -u(username):(password) -D h.txt -XGET (protocol)://<domain>/api/npm/auth
```
You should see the value of the *Server* response header in the *h.txt* file created by the command.

The context of h.txt should look like:
```
$ cat h.txt 
HTTP/1.1 200 OK
Server: Artifactory/6.5.2
X-Artifactory-Id: b4a6593a29a55c51:-5c6b4d16:16851fc6fbe:-8000
Content-Type: text/plain
Transfer-Encoding: chunked
Date: Sun, 20 Jan 2019 15:41:11 GMT
```

We're considering to replace reading the the version from the header by sending a separate rest request to retrieve the version. We implemented this mechanism to avoid sending an additional request to fetch the version.

Please let us know what you see on your side.

**Comment by marcwittke** [comment]
```
HTTP/2 200
server: nginx/1.14.1
date: Tue, 22 Jan 2019 10:55:29 GMT
content-type: text/plain
x-artifactory-id: 21374b7d2da9ee82:-25281522:167330b0df9:-8000
x-cxn-node: hub
x-cxn-forwarded-for: 80.151.77.68
x-cxn-vhost: hub.chemaxon.com
```

from my side there is definitely no proxy in play. But the reverse nginx on chemaxon's side might mess things up, though

**Comment by marcwittke** [comment]
@chemaxon, @bzaicsek-cxn this might be interesting for you, since I came here using your https://github.com/ChemAxon/marvinjs-angular4-example

**Comment by bzaicsek-cxn** [comment]
@marcwittke We have an nginx in front of Artifactory. I am contacting IT department to look at your issue.

**Comment by bzaicsek-cxn** [comment]
@marcwittke We could not reproduce the issue. We have done the following steps:

    curl -o ~/.npmrc -u<my-email-address>:<my-API-key> https://hub.chemaxon.com/artifactory/api/npm/auth
    npm config set registry https://hub.chemaxon.com/artifactory/api/npm/npm/

you could follow the guide with automatically filed data on the following page: https://chemaxon.com/products/marvin-live/download

BTW, the build script was updated: https://github.com/ChemAxon/marvinjs-angular4-example/commit/9e06b7cdfdfa9f353df181bad00e03529eee7dd2 (two css files are no longer part of MarvinJS release)

**Comment by marcwittke** [comment]
```
HTTP/2 200
date: Wed, 23 Jan 2019 15:29:28 GMT
content-type: text/plain
server: Artifactory/6.5.3
x-artifactory-id: 21374b7d2da9ee82:-25281522:167330b0df9:-8000
x-cxn-node: hub
x-cxn-forwarded-for: 80.151.77.68
x-cxn-vhost: hub.chemaxon.com
```

thanks, problem solved.
