### ISSUE TITLE
Nuget restore fail when project root dir include more than one .sln file.

### ISSUE THREAD

**Issue by yudkeh** [jfrog/artifactory-vsts-extension#70]
Since we pass the project root dir and not the path to the select .sln file to JFrog CLI, when we execute "nuget restore" the client complain about the fact that there are few .sln files.

In order to fix the issue, we need to pass the full path to the .sln file which we selecting at the task configuration.

**Comment by yudkeh** [comment]
In order to resolve the issue, we need to add the relevant .sln file name as the first argument in the "Artifactory NuGet restore" task "Arguments".

**Comment by eyalbe4** [comment]
The relevant label and description in *Artifactory Nuget*'s task had been updated. See https://github.com/jfrog/artifactory-vsts-extension/commit/24a3148e322f3caacdd8804c2258ebb1e7b88418
This will be included as part of the upcoming release.
