### ISSUE TITLE
Artifactory Docker pull task fails

### ISSUE THREAD

**Issue by prasannanjfrog** [jfrog/artifactory-vsts-extension#72]
Artifactory Docker pull task fails with the following error 

"no matching manifest for unknown in the manifest list entries"

Please review the attached log file for the entire log trace. The CLI version installed was 1.23.1. 

Tried the same command on a windows server with the same version of CLI, it works without any issues. Hence it does not look like its an issue with the CLI.

Looks like its an issue with the agent pool. 

The issue occurs on using the agent Pool: **Hosted VS2017**. However, it works fine with agent pool: **Hosted ubuntu 1604**

[dockertask.log](https://github.com/jfrog/artifactory-vsts-extension/files/3114429/dockertask.log)

**Comment by barbelity** [comment]
Hi @prasannanjfrog, I believe that the agent you receive from 'Hosted Vs2017' doesn't support the image you are trying to pull.
There are several differences in the way docker runs on ubuntu / windows. For example, [this issue in stackoverflow](https://stackoverflow.com/questions/48066994/docker-no-matching-manifest-for-windows-amd64-in-the-manifest-list-entries).
As you suggested, it doesn't seem to be an issue in JFrog CLI.
