### ISSUE TITLE
Go support

### ISSUE THREAD

**Issue by jpreese** [jfrog/artifactory-vsts-extension#82]
Looking at the available tasks, I'm not seeing an implementation for Go.

**Comment by eyalbe4** [comment]
@jpreese,
This is indeed something that we would like see added in the future.

**Comment by RobiNino** [comment]
[Artifactory Go task](https://www.jfrog.com/confluence/display/RTF/Azure+DevOps+and+TFS+Artifactory+Extension#AzureDevOpsandTFSArtifactoryExtension-TriggeringGoBuilds) was now added, in version 1.7.2 of the extension.
Any feedback would be much appreciated, @jpreese .
